# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTeihrSFk3IZNBzHyOPRDxmyuL9PKnWU
"""

!pip install --quiet langchain==1.3.1 langchain-community==0.4.1 langchain-core==1.4.0 langchain-text-splitters==1.1.2 langchain-classic==1.0.7 langchain-huggingface langchain-google-genai sentence-transformers chromadb pypdf "pydantic<=2.12.3" "numpy<2.1" opentelemetry-api opentelemetry-sdk langchain-xai[cite: 1]

import sys
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_core.prompts import ChatPromptTemplate[cite: 1]

if 'google.colab' in sys.modules:
    import IPython
    app = IPython.Application.instance()
    app.kernel.do_shutdown(True)[cite: 1]

pdf_path = "/content/drive/MyDrive/rag doc/Standard Chartered Bank.pdf"
loader = PyPDFLoader(pdf_path)
pages = loader.load()[cite: 1]

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50,
    separators=["\n\n", "\n", " ", ""]
)
chunks = text_splitter.split_documents(pages)[cite: 1]

for i in range(10):
    if i < len(chunks):
        print(chunks[i].page_content)[cite: 1]

embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")[cite: 1]

vector_db = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings,
    persist_directory="/content/drive/MyDrive/rag_db"
)[cite: 1]

system_prompt = (
    "You are an assistant for question-answering tasks. "
    "Use the following pieces of retrieved context to answer the question. "
    "If you don't know the answer, say that you don't know. "
    "Use three sentences maximum and keep the answer concise.\n\n"
    "Context: {context}"
)[cite: 1]

prompt_template = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    ("human", "{input}"),
])[cite: 1]